import{loadData,provinces,provinceDraws,nextScheduledDate}from"./data.js";import{predict}from"./model.js";import{predict6}from"./model6.js";import{predictOtherPrizes}from"./model-prizes.js";import{backtest}from"./backtest.js";import{backtest6}from"./backtest6.js";import{backtestOtherPrizes,backtestChampionChallenger}from"./backtest-prizes.js?v=2";import*as store from"./storage.js";
let data,dataHash="",current=null,current6=null,currentOther=null;const forecastCache=new Map(),$=s=>document.querySelector(s),fmt=x=>(100*x).toFixed(1)+"%",runtime=p=>p._runtime?" · "+(p._runtime.cached?"từ bộ nhớ tạm":(p._runtime.ms/1000).toFixed(2)+" giây"):"";
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="saved")renderSaved()});
function draws(){return provinceDraws(data,$("#province").value)}
async function fingerprint(rows){const text=JSON.stringify(rows),bytes=new TextEncoder().encode(text);if(crypto.subtle){const hash=await crypto.subtle.digest("SHA-256",bytes);return[...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("").slice(0,16)}let h=2166136261;for(const b of bytes)h=Math.imul(h^b,16777619);return(h>>>0).toString(16).padStart(8,"0")}
function renderDataHealth(){const ds=draws(),last=ds.at(-1)?.date,next=nextScheduledDate(ds),age=last?Math.floor((Date.now()-new Date(last+"T00:00:00Z"))/86400000):null,status=age===null?"bad":age<=8?"good":age<=15?"neutral":"bad",label=age===null?"Thiếu dữ liệu":age<=8?"Dữ liệu mới":age<=15?"Cần cập nhật":"Dữ liệu đã cũ";$("#dataHealth").innerHTML='<div class="health-head"><b>🛡️ Chất lượng dữ liệu</b><span class="signal '+status+'">'+label+'</span></div><div class="health-grid"><span><small>Tỉnh đã chọn</small><b>'+ds.length+' kỳ</b></span><span><small>Kết quả cuối</small><b>'+(last||"—")+'</b></span><span><small>Kỳ dự kiến</small><b>'+(next||"—")+'</b></span><span><small>Mã dữ liệu</small><b class="mono">'+(dataHash||"đang tính…")+'</b></span></div><p class="muted">Toàn bộ nguồn: '+data.quality.valid+" hợp lệ · "+data.quality.invalid+" lỗi · "+data.quality.duplicate+" trùng."+(age>15?" Dự báo hiện chỉ dành cho kỳ kế tiếp sau ngày dữ liệu cuối, không phải kỳ hiện tại.":"")+"</p>"}
function reset(){current=current6=currentOther=null;$("#ranking").innerHTML="";$("#ranking6").innerHTML="";$("#otherPrizeResults").innerHTML="";$("#otherPrizeMeta").innerHTML="";$("#saveForecast").disabled=$("#save6").disabled=$("#saveOtherPrizes").disabled=true}
function render2(p){$("#forecastMeta").innerHTML='<p class="muted">'+p.trainingSize+" kỳ · "+p.version+runtime(p)+"</p>";$("#ranking").innerHTML=p.ranking.slice(0,10).map(x=>'<div class="number"><small>#'+x.rank+"</small><strong>"+x.number+"</strong><small>"+fmt(x.score)+"</small></div>").join("");$("#saveForecast").disabled=false}
function render6(p){$("#meta6").innerHTML='<p class="muted">'+p.trainingSize+" kỳ · "+p.candidatesEvaluated+" ứng viên · "+p.version+runtime(p)+"</p>";$("#ranking6").className="six-list";$("#ranking6").innerHTML=p.ranking.slice(0,10).map(x=>'<div class="six-row"><b>#'+x.rank+'</b><span class="six-number">'+x.number+"</span><span>"+fmt(x.relativeWeight)+'</span><div class="six-detail">Tổng '+x.sum+" · Cặp "+x.pairs.join(" | ")+" · Bộ ba "+x.triples.join(" | ")+"</div></div>").join("");$("#save6").disabled=false}
function renderOther(p){$("#otherPrizeMeta").innerHTML='<p class="muted">'+p.trainingSize+" kỳ · "+p.version+runtime(p)+" · mỗi hạng 1 dãy đại diện</p>";$("#otherPrizeResults").innerHTML=p.tiers.map(x=>'<div class="prize-result"><span class="prize-name">'+x.label+'</span><strong class="prize-number">'+x.representative+'</strong><small class="prize-note">Tổng '+x.sum+" · "+x.observations+" mẫu</small></div>").join("");$("#saveOtherPrizes").disabled=false}
async function runJob(buttonId,kind,compute,render,assign){const btn=$(buttonId),label=btn.textContent,key=[kind,$("#province").value,$("#window").value,draws().at(-1)?.date].join("|");btn.disabled=true;btn.classList.add("busy");btn.textContent="Đang xử lý…";await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));try{let result=forecastCache.get(key),cached=!!result;const start=performance.now();if(!result){result=compute();forecastCache.set(key,result)}const shown={...result,_runtime:{cached,ms:performance.now()-start}};assign(result);render(shown)}catch(e){alert(e.message)}finally{btn.disabled=false;btn.classList.remove("busy");btn.textContent=label}}
$("#run6").onclick=()=>runJob("#run6","db6",()=>predict6(draws(),{window:+$("#window").value}),render6,x=>current6=x);
$("#runOtherPrizes").onclick=()=>runJob("#runOtherPrizes","other",()=>predictOtherPrizes(draws(),{window:+$("#window").value}),renderOther,x=>currentOther=x);
$("#runForecast").onclick=()=>runJob("#runForecast","tail2",()=>predict(draws(),{window:+$("#window").value}),render2,x=>current=x);
function savePrediction(p,type){const top=p.ranking.slice(0,10).map(x=>x.number);store.save({province:$("#province").value,targetDate:nextScheduledDate(draws()),version:p.version,type,window:p.window,trainingThrough:draws().at(-1).date,dataHash,top});renderSaved();alert("Đã lưu dự báo "+type)}
$("#save6").onclick=()=>{try{savePrediction(current6,"6 số")}catch(e){alert(e.message)}};$("#saveForecast").onclick=()=>{try{savePrediction(current,"2 số")}catch(e){alert(e.message)}};
$("#saveOtherPrizes").onclick=()=>{try{if(!currentOther)throw new Error("Hãy chạy dự báo 8 giải trước");const predictions=Object.fromEntries(currentOther.tiers.map(x=>[x.key,x.representative]));store.save({province:$("#province").value,targetDate:nextScheduledDate(draws()),version:currentOther.version,type:"8 giải",window:currentOther.window,trainingThrough:draws().at(-1).date,dataHash,predictions});renderSaved();alert("Đã lưu dự báo 8 giải để kiểm định")}catch(e){alert(e.message)}};
$("#runBacktest6").onclick=async()=>{const btn=$("#runBacktest6");btn.disabled=true;$("#backtestStatus").textContent="Đang kiểm định mô hình 6 số và ablation 8 giải…";try{const r=await backtest6(draws(),{testSize:+$("#testSize").value,window:+$("#window").value,onProgress:(a,b)=>$("#backtestStatus").textContent="6 số: "+a+"/"+b+" kỳ"}),f=r.full,w=r.withoutCrossPrize,d=r.delta;$("#backtestStatus").textContent="Hoàn tất. Δ dương nghĩa là tín hiệu 8 giải giúp cải thiện.";$("#metrics6").innerHTML='<h3>Kết quả 6 số + Ablation</h3><table><tr><th>Mô hình</th><th>Exact@10</th><th>Exact@50</th><th>Đúng vị trí</th><th>≥3/6</th><th>AB@10</th><th>CD@10</th><th>EF@10</th></tr>'+[["Đủ 9 hạng giải",f],["Chỉ giải ĐB",w]].map(([n,x])=>"<tr><td>"+n+"</td><td>"+fmt(x.exact10)+"</td><td>"+fmt(x.exact50)+"</td><td>"+fmt(x.positionAccuracy)+"</td><td>"+fmt(x.threePlus)+"</td><td>"+fmt(x.pairAB)+"</td><td>"+fmt(x.pairCD)+"</td><td>"+fmt(x.pairEF)+"</td></tr>").join("")+'</table><p class="muted">Chênh lệch do 8 giải phụ: đúng vị trí <b>'+((d.positionAccuracy*100).toFixed(1))+" điểm %</b> · ≥3/6 <b>"+((d.threePlus*100).toFixed(1))+" điểm %</b> · EF <b>"+((d.pairEF*100).toFixed(1))+" điểm %</b>.</p>"}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false}};
$("#runBacktest").onclick=async()=>{const btn=$("#runBacktest");btn.disabled=true;$("#backtestStatus").textContent="Đang kiểm định 2 số…";try{const r=await backtest(draws(),{testSize:+$("#testSize").value,window:+$("#window").value});$("#backtestStatus").textContent="Hoàn tất kiểm định 2 số.";$("#metrics").innerHTML='<h3>Kết quả 2 số</h3><table><tr><th>Mô hình</th><th>Hit@1</th><th>Hit@5</th><th>Hit@10</th><th>MRR</th><th>Brier</th></tr>'+Object.entries(r).map(([k,v])=>"<tr><td>"+k+"</td><td>"+fmt(v.hit1)+"</td><td>"+fmt(v.hit5)+"</td><td>"+fmt(v.hit10)+"</td><td>"+v.mrr.toFixed(3)+"</td><td>"+v.brier.toFixed(3)+"</td></tr>").join("")+"</table>"}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false}};
$("#runBacktestPrizes").onclick=async()=>{const btn=$("#runBacktestPrizes");btn.disabled=true;btn.classList.add("busy");$("#backtestStatus").textContent="Đang kiểm định lịch sử 8 giải…";await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));try{const r=await backtestOtherPrizes(draws(),{testSize:+$("#testSize").value,window:+$("#window").value,onProgress:(a,b)=>$("#backtestStatus").textContent="8 giải: "+a+"/"+b+" kỳ"}),counts=r.rows.reduce((a,x)=>(a[x.status]++,a),{"Tốt":0,"Trung tính":0,"Kém":0});$("#backtestStatus").textContent="Hoàn tất "+r.trials+" kỳ thực tế.";$("#metricsPrizes").innerHTML='<h3>Kết quả 8 giải đại diện</h3><div class="test-summary"><strong>'+r.trials+' kỳ thực tế</strong><span>Yêu cầu '+r.requestedTrials+" kỳ · giữ "+r.minimumTraining+' kỳ đầu để huấn luyện</span><div><b class="signal good">Tốt '+counts["Tốt"]+'</b><b class="signal neutral">Trung tính '+counts["Trung tính"]+'</b><b class="signal bad">Kém '+counts["Kém"]+"</b></div></div><table><tr><th>Giải</th><th>Trùng dãy</th><th>Ngẫu nhiên</th><th>Đúng vị trí</th><th>Vị trí ngẫu nhiên</th><th>Trùng 2 cuối</th><th>Khoảng tin cậy 95%</th><th>2 cuối ngẫu nhiên</th><th>Đánh giá</th></tr>"+r.rows.map(x=>'<tr><td>'+x.label+"</td><td>"+fmt(x.exactRate)+"</td><td>"+fmt(x.randomExactRate)+"</td><td>"+fmt(x.positionAccuracy)+"</td><td>"+fmt(x.randomPositionAccuracy)+"</td><td>"+fmt(x.tail2Rate)+"</td><td>"+fmt(x.confidenceLow)+" – "+fmt(x.confidenceHigh)+"</td><td>"+fmt(x.randomTail2Rate)+'</td><td><b class="signal '+(x.status==="Tốt"?"good":x.status==="Kém"?"bad":"neutral")+'">'+x.status+"</b></td></tr>").join("")+'</table><p class="muted"><b>Cách đọc:</b> nhãn “Tốt” chỉ xuất hiện khi toàn bộ khoảng tin cậy 95% của tỷ lệ trùng hai số cuối cao hơn mức ngẫu nhiên; “Kém” khi toàn bộ khoảng thấp hơn. Đây là đánh giá sàng lọc, chỉ nên tin khi cùng kết luận lặp lại ở nhiều cửa sổ. “Vị trí ngẫu nhiên” đã điều chỉnh theo số kết quả thật của từng giải.</p>'}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false;btn.classList.remove("busy")}};
$("#runChampion").onclick=async()=>{const btn=$("#runChampion");btn.disabled=true;btn.classList.add("busy");$("#backtestStatus").textContent="Đang so sánh Champion và Challenger…";await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));try{const r=await backtestChampionChallenger(draws(),{testSize:+$("#testSize").value,window:+$("#window").value,onProgress:(a,b)=>$("#backtestStatus").textContent="Champion–Challenger: "+a+"/"+b+" kỳ"}),d=r.delta;$("#backtestStatus").textContent="Hoàn tất "+r.trials+" kỳ. "+r.decision+".";$("#metricsChampion").innerHTML='<h3>Champion–Challenger</h3><div class="test-summary"><strong>'+r.decision+'</strong><span>'+r.trials+' kỳ thực tế · '+r.champion.total+' lượt giải được chấm</span></div><table><tr><th>Mô hình</th><th>Trùng dãy</th><th>Trùng 2 cuối</th><th>Đúng vị trí</th></tr><tr><td>Champion hiện tại</td><td>'+fmt(r.champion.exactRate)+'</td><td>'+fmt(r.champion.tail2Rate)+'</td><td>'+fmt(r.champion.positionAccuracy)+'</td></tr><tr><td>Challenger ưu tiên kỳ gần</td><td>'+fmt(r.challenger.exactRate)+'</td><td>'+fmt(r.challenger.tail2Rate)+'</td><td>'+fmt(r.challenger.positionAccuracy)+'</td></tr><tr><td>Chênh lệch</td><td>'+((d.exactRate*100).toFixed(1))+' điểm %</td><td>'+((d.tail2Rate*100).toFixed(1))+' điểm %</td><td>'+((d.positionAccuracy*100).toFixed(1))+' điểm %</td></tr></table><p class="muted"><b>Quy tắc:</b> chỉ đề xuất Challenger khi có ít nhất 50 kỳ, không giảm trùng dãy và đồng thời tăng ít nhất 1 điểm % ở trùng 2 số cuối lẫn đúng vị trí. App không tự đổi mô hình dự báo chính.</p>'}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false;btn.classList.remove("busy")}};
function statusBadge(status){return '<b class="signal '+(status==="Tốt"?"good":status==="Kém"?"bad":"neutral")+'">'+status+"</b>"}
$("#runStability").onclick=async()=>{const btn=$("#runStability"),sizes=[30,50,90],results=[];btn.disabled=true;btn.classList.add("busy");$("#backtestStatus").textContent="Đang so sánh độ ổn định 30–50–90 kỳ…";await new Promise(r=>requestAnimationFrame(()=>setTimeout(r,0)));try{for(const size of sizes){$("#backtestStatus").textContent="Đang kiểm định cửa sổ "+size+" kỳ…";results.push(await backtestOtherPrizes(draws(),{testSize:size,window:+$("#window").value,onProgress:(a,b)=>$("#backtestStatus").textContent="Cửa sổ "+size+": "+a+"/"+b+" kỳ"}))}const byKey=Object.fromEntries(results[0].rows.map(x=>[x.key,results.map(r=>r.rows.find(y=>y.key===x.key))]));$("#backtestStatus").textContent="Hoàn tất so sánh "+results.map(r=>r.trials).join("–")+" kỳ thực tế.";$("#metricsStability").innerHTML='<h3>Độ ổn định qua nhiều cửa sổ</h3><table><tr><th>Giải</th>'+results.map(r=>"<th>"+r.trials+" kỳ</th>").join("")+'<th>Kết luận</th></tr>'+Object.entries(byKey).map(([key,rows])=>{const notable=rows.every(x=>x.status===rows[0].status&&x.status!=="Trung tính"),conclusion=notable?(rows[0].status==="Tốt"?"Tín hiệu tốt ổn định":"Tín hiệu kém ổn định"):"Chưa đủ ổn định";return "<tr><td>"+rows[0].label+"</td>"+rows.map(x=>"<td>"+fmt(x.tail2Rate)+"<br>"+statusBadge(x.status)+"</td>").join("")+"<td><b>"+conclusion+"</b></td></tr>"}).join("")+'</table><p class="muted"><b>Cách đọc:</b> tỷ lệ trong mỗi ô là mức trùng hai số cuối. Chỉ xem là tín hiệu ổn định khi cùng kết luận Tốt hoặc Kém xuất hiện ở cả ba cửa sổ và từng cửa sổ đều vượt kiểm tra khoảng tin cậy 95%. “Chưa đủ ổn định” không có nghĩa là chắc chắn không hiệu quả; chỉ là dữ liệu hiện tại chưa đủ bằng chứng.</p>'}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false;btn.classList.remove("busy")}};
const PRIZE_LABELS={g8:"G8",g7:"G7",g6:"G6",g5:"G5",g4:"G4",g3:"G3",g2:"G2",g1:"G1"},PRIZE_KEYS=Object.keys(PRIZE_LABELS);
function findActual(x){return data.draws.find(d=>d.province===x.province&&d.date===x.targetDate)}
function prizeEvaluation(x,d){const details=PRIZE_KEYS.map(key=>{const actual=Array.isArray(d.prizes?.[key])?d.prizes[key]:[],predicted=x.predictions?.[key]||"",hit=actual.includes(predicted);return{key,predicted,actual,hit}});return{details,hits:details.filter(z=>z.hit).length}}
function renderPrizeSummary(rows){const resolved=rows.filter(x=>x.type==="8 giải").map(x=>({x,d:findActual(x)})).filter(z=>z.d);if(!resolved.length){$("#savedSummary").innerHTML='<p class="muted">Chưa có kỳ dự báo 8 giải nào đến ngày đối chiếu.</p>';return}const stats=Object.fromEntries(PRIZE_KEYS.map(k=>[k,{hit:0,total:0}]));let hits=0;for(const {x,d}of resolved){for(const z of prizeEvaluation(x,d).details){stats[z.key].total++;if(z.hit){stats[z.key].hit++;hits++}}}$("#savedSummary").innerHTML='<div class="score-summary"><b>'+resolved.length+' kỳ đã đối chiếu</b><strong>'+hits+"/"+(resolved.length*8)+'</strong><span>Dãy khớp đúng hạng giải</span></div><div class="tier-stats">'+PRIZE_KEYS.map(k=>'<span>'+PRIZE_LABELS[k]+' <b>'+stats[k].hit+"/"+stats[k].total+"</b></span>").join("")+"</div>"}
function audit(x){return'<small class="audit">Mã dữ liệu: '+(x.dataHash||"bản cũ chưa có mã")+" · lưu "+new Date(x.savedAt).toLocaleString("vi-VN")+"</small>"}
function renderSaved(){
 const rows=store.list();
 renderPrizeSummary(rows);
 $("#savedList").innerHTML=rows.length?rows.map(x=>{
  const d=findActual(x);
  if(x.type==="8 giải"){
   if(!d)return "<div class='saved-item'><b>8 giải · "+x.province+" · "+x.targetDate+"</b><br><span class='muted'>"+x.version+" · Đang chờ kết quả</span>"+audit(x)+"</div>";
   const e=prizeEvaluation(x,d);
   const details=e.details.map(z=>"<div class='"+(z.hit?"hit":"miss")+"'><b>"+PRIZE_LABELS[z.key]+"</b><span>Dự báo "+z.predicted+"</span><span>Thực tế "+z.actual.join(" / ")+"</span><strong>"+(z.hit?"✓ Khớp":"✕ Không khớp")+"</strong></div>").join("");
   return "<div class='saved-item'><b>8 giải · "+x.province+" · "+x.targetDate+" · "+e.hits+"/8 dãy khớp</b>"+audit(x)+"<div class='saved-prizes'>"+details+"</div></div>";
  }
  const actual=d?(x.type==="6 số"?d.db:d.tail):null,rank=actual?x.top.indexOf(actual)+1:null;
  return "<div class='saved-item'><b>"+(x.type||"2 số")+" · "+x.province+" · "+x.targetDate+"</b><br><span class='muted'>"+x.version+" · Top: "+x.top.join(", ")+"</span>"+audit(x)+"<br>"+(actual?"Thực tế: <b>"+actual+"</b> · "+(rank?"Hạng "+rank:"Ngoài Top 10"):"Chưa có kết quả")+"</div>";
 }).join(""):"<p class='muted'>Chưa có dự báo đã lưu.</p>";
}
async function init(){try{data=await loadData();const ps=provinces(data);$("#province").innerHTML=ps.map(p=>'<option value="'+p+'">'+p.replaceAll("-"," ")+"</option>").join("");$("#dataState").textContent=data.quality.valid+" kỳ hợp lệ · "+ps.length+" tỉnh · đủ 9 hạng giải";renderDataHealth();dataHash=await fingerprint(data.draws);renderDataHealth();$("#province").onchange=()=>{reset();renderDataHealth()};$("#window").onchange=reset;if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js")}catch(e){$("#dataState").textContent="Lỗi dữ liệu";document.querySelector("main").innerHTML='<div class="card warning">'+e.message+"</div>"}}init();