import{loadData,provinces,provinceDraws,nextScheduledDate}from"./data.js";import{predict}from"./model.js";import{backtest}from"./backtest.js";import*as store from"./storage.js";
let data,current=null;const $=s=>document.querySelector(s),fmt=x=>(100*x).toFixed(1)+"%";
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab).classList.add("active");if(b.dataset.tab==="saved")renderSaved()});
function draws(){return provinceDraws(data,$("#province").value)}
function renderPrediction(p){$("#forecastMeta").innerHTML='<p class="muted">Huấn luyện: <b>'+p.trainingSize+'</b> kỳ · Cửa sổ: <b>'+p.window+'</b> · '+p.version+"</p>";$("#ranking").innerHTML=p.ranking.slice(0,10).map(x=>'<div class="number"><small>#'+x.rank+'</small><strong>'+x.number+'</strong><small>'+fmt(x.score)+'</small></div>').join("");$("#saveForecast").disabled=false}
$("#runForecast").onclick=()=>{try{current=predict(draws(),{window:+$("#window").value});renderPrediction(current)}catch(e){alert(e.message)}};
$("#saveForecast").onclick=()=>{try{store.save({province:$("#province").value,targetDate:nextScheduledDate(draws()),version:current.version,window:current.window,trainingThrough:draws().at(-1).date,top:current.ranking.slice(0,10).map(x=>x.number),probabilities:current.probabilities});renderSaved();alert("Đã lưu dự báo")}catch(e){alert(e.message)}};
$("#runBacktest").onclick=async()=>{const btn=$("#runBacktest");btn.disabled=true;$("#backtestStatus").textContent="Đang chạy…";try{const r=await backtest(draws(),{testSize:+$("#testSize").value,window:+$("#window").value,onProgress:(a,b)=>$("#backtestStatus").textContent="Đã kiểm tra "+a+"/"+b+" kỳ"});$("#backtestStatus").textContent="Hoàn tất. Giá trị tốt: Hit/MRR cao, Brier thấp.";$("#metrics").innerHTML='<table><thead><tr><th>Mô hình</th><th>Hit@1</th><th>Hit@5</th><th>Hit@10</th><th>MRR</th><th>Brier</th></tr></thead><tbody>'+Object.entries(r).map(([k,v])=>'<tr><td>'+k+'</td><td>'+fmt(v.hit1)+'</td><td>'+fmt(v.hit5)+'</td><td>'+fmt(v.hit10)+'</td><td>'+v.mrr.toFixed(3)+'</td><td>'+v.brier.toFixed(3)+'</td></tr>').join("")+"</tbody></table>"}catch(e){$("#backtestStatus").textContent=e.message}finally{btn.disabled=false}};
function renderSaved(){const rows=store.reconcile(store.list(),data.draws);$("#savedList").innerHTML=rows.length?rows.map(x=>'<div class="saved-item"><b>'+x.province+" · "+x.targetDate+'</b><br><span class="muted">'+x.version+" · Top: "+x.top.join(", ")+"</span><br>"+(x.actual?"Thực tế: <b>"+x.actual+"</b> · "+(x.rank?"Hạng "+x.rank:"Ngoài Top 10"):"Chưa có kết quả")+"</div>").join(""):'<p class="muted">Chưa có dự báo đã lưu.</p>'}
async function init(){try{data=await loadData();const ps=provinces(data);$("#province").innerHTML=ps.map(p=>'<option value="'+p+'">'+p.replaceAll("-"," ")+"</option>").join("");$("#dataState").textContent=data.draws.length+" kỳ · "+ps.length+" tỉnh";$("#province").onchange=()=>{current=null;$("#ranking").innerHTML="";$("#saveForecast").disabled=true};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js")}catch(e){$("#dataState").textContent="Lỗi dữ liệu";document.querySelector("main").innerHTML='<div class="card warning">'+e.message+"</div>"}}init();