export const SOURCE_URL="https://raw.githubusercontent.com/Thienlee86/du-bao-xsmn/main/data/xsmn_seed.json";
export const PRIZE_SCHEMA={db:{count:1,digits:6},g1:{count:1,digits:5},g2:{count:1,digits:5},g3:{count:2,digits:5},g4:{count:7,digits:5},g5:{count:1,digits:4},g6:{count:3,digits:4},g7:{count:1,digits:3},g8:{count:1,digits:2}};
const arr=x=>Array.isArray(x)?x:[x];
function normalizePrizes(raw){const out={};for(const[k,s]of Object.entries(PRIZE_SCHEMA)){const source=arr(raw?.[k]);if(source.length!==s.count||source.some(x=>x===null||x===undefined||String(x).trim()===""))return null;const values=source.map(x=>String(x).trim().padStart(s.digits,"0"));if(values.some(x=>!new RegExp("^\\d{"+s.digits+"}$").test(x)))return null;out[k]=values}return out}
export function boardNumbers(draw,{includeDb=true}={}){return Object.entries(draw.prizes).filter(([k])=>includeDb||k!=="db").flatMap(([,v])=>v)}
export function boardTails(draw,{includeDb=true}={}){return boardNumbers(draw,{includeDb}).map(x=>x.slice(-2))}
export async function loadData(){const r=await fetch(SOURCE_URL,{cache:"no-store"});if(!r.ok)throw new Error("Không tải được dữ liệu nguồn");return normalize(await r.json())}
export function normalize(raw){if(!Array.isArray(raw.draws))throw new Error("JSON thiếu mảng draws");const seen=new Set(),quality={input:raw.draws.length,invalid:0,duplicate:0};const draws=raw.draws.map(d=>{const province=String(d.province??""),date=String(d.date??""),prizes=normalizePrizes(d.prizes),key=province+"|"+date;if(!province||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!prizes){quality.invalid++;return null}if(seen.has(key)){quality.duplicate++;return null}seen.add(key);const db=prizes.db[0];return{province,date,db,tail:db.slice(-2),prizes}}).filter(Boolean).sort((a,b)=>a.date.localeCompare(b.date));if(draws.length<100)throw new Error("Dữ liệu hợp lệ quá ít");quality.valid=draws.length;return{draws,generatedAt:raw.generatedAt??null,quality}}
export function provinces(data){return[...new Set(data.draws.map(d=>d.province))].sort()}
export function provinceDraws(data,id){return data.draws.filter(d=>d.province===id)}
export function nextScheduledDate(draws){const last=draws.at(-1)?.date;if(!last)return null;const d=new Date(last+"T00:00:00Z");d.setUTCDate(d.getUTCDate()+7);return d.toISOString().slice(0,10)}
