export const MODEL6_VERSION="hierarchical-6d-v1.0.0";
const digits=()=>Array.from({length:10},(_,i)=>String(i));
const sum6=s=>[...s].reduce((a,b)=>a+Number(b),0);
function positionModels(sample){return Array.from({length:6},(_,p)=>{const c=Array(10).fill(1);sample.forEach(d=>c[+d.db[p]]++);const z=c.reduce((a,b)=>a+b);return c.map(x=>x/z)})}
function ngrams(sample,n){return Array.from({length:7-n},(_,p)=>{const c=new Map();sample.forEach(d=>{const k=d.db.slice(p,p+n);c.set(k,(c.get(k)||0)+1)});return c})}
function smoothed(map,key,total,vocab,alpha=.5){return((map.get(key)||0)+alpha)/(total+alpha*vocab)}
function topDigits(pos,k=6){return pos.map((p,i)=>digits().map((d,j)=>({d,p:j in p?p[j]:0})).sort((a,b)=>b.p-a.p).slice(0,k).map(x=>x.d))}
function cartesian(groups,at=0,prefix="",out=[]){if(at===groups.length){out.push(prefix);return out}for(const d of groups[at])cartesian(groups,at+1,prefix+d,out);return out}
export function predict6(draws,{window=100,beamDigits=6,top=50}={}){if(draws.length<20)throw new Error("Cần ít nhất 20 kỳ để dự báo 6 số");const sample=draws.slice(-Math.min(window,draws.length));const pos=positionModels(sample),pairs=ngrams(sample,2),triples=ngrams(sample,3),sums=Array(55).fill(1);sample.forEach(d=>sums[sum6(d.db)]++);const sumZ=sums.reduce((a,b)=>a+b);const candidates=cartesian(topDigits(pos,beamDigits));const scored=candidates.map(number=>{let lp=0;for(let p=0;p<6;p++)lp+=.46*Math.log(pos[p][+number[p]]);for(let p=0;p<5;p++)lp+=.07*Math.log(smoothed(pairs[p],number.slice(p,p+2),sample.length,100));for(let p=0;p<4;p++)lp+=.025*Math.log(smoothed(triples[p],number.slice(p,p+3),sample.length,1000));lp+=.09*Math.log(sums[sum6(number)]/sumZ);return{number,score:lp,sum:sum6(number),pairs:[number.slice(0,2),number.slice(2,4),number.slice(4,6)],triples:[number.slice(0,3),number.slice(3,6)]}}).sort((a,b)=>b.score-a.score).slice(0,top);const max=scored[0].score,weights=scored.map(x=>Math.exp(x.score-max)),z=weights.reduce((a,b)=>a+b);scored.forEach((x,i)=>{x.relativeWeight=weights[i]/z;x.rank=i+1});return{version:MODEL6_VERSION,window,trainingSize:draws.length,beamDigits,candidatesEvaluated:candidates.length,ranking:scored,positionTop:topDigits(pos,3)}}
export function explain6(item){return{sum:item.sum,pairs:item.pairs,triples:item.triples}}
